name: Build and Push

on:
  push:
    branches:
      - master
jobs:
  job1:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t $LOGIN/$NAME:latest .
      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      - name: Push image
        run: docker push $LOGIN/$NAME:latest
      - name: Restart
        run: wget --post-data="" ${{ secrets.CD_PORTAINER_WEBHOOK }}
